name: Nodejs Build Template
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        description: 'The Nodejs version to use for the build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install